### ISSUE TITLE
User Account Details

### ISSUE THREAD

**Issue by dustintitus** [dustintitus/share#10]
I'd also like a place for users to modify their account details. This should be accomplished from the main menu.
![screen shot 2016-04-26 at 1 46 22 pm](https://cloud.githubusercontent.com/assets/925983/14828554/6f03222c-0bb5-11e6-8c47-ab631c08e454.png)

**Comment by saurabhitc** [comment]
Done
![userdetail](https://cloud.githubusercontent.com/assets/18684955/14878439/3b17cc64-0d41-11e6-9ac4-e308591bd3b9.PNG)
