### ISSUE TITLE
Record deletion

### ISSUE THREAD

**Issue by dustintitus** [dustintitus/share#11]
I would like to have the ability to delete records from the database. Could we add a button that allows a user to do that?

![screen shot 2016-04-27 at 12 35 51 pm](https://cloud.githubusercontent.com/assets/925983/14859998/ac278ebc-0c74-11e6-8dc4-7cfeb86fb8db.png)

**Comment by saurabhitc** [comment]
Functionality Added
![capture](https://cloud.githubusercontent.com/assets/18684955/14954628/976f2e96-1091-11e6-81bd-4c1b473ea063.PNG)
