### ISSUE TITLE
All pages - header navigation

### ISSUE THREAD

**Issue by dustintitus** [dustintitus/share#9]
Can we add a small header navigation that allows for users to go back to the main menu at any point in time?
![screen shot 2016-04-26 at 1 46 22 pm](https://cloud.githubusercontent.com/assets/925983/14828534/5cd6b244-0bb5-11e6-840e-9d38a5762cf1.png)

**Comment by saurabhitc** [comment]
added 
![navbar](https://cloud.githubusercontent.com/assets/18684955/14846841/667b5e48-0c83-11e6-9b01-1a976a296e99.PNG)
